DROP FUNCTION IF EXISTS `FN_EMPTY`;
DELIMITER //
CREATE FUNCTION `FN_EMPTY`(`P_Str` VARCHAR(1024)) RETURNS tinyint(4)
    NO SQL
    SQL SECURITY INVOKER
    DETERMINISTIC
BEGIN
	IF P_Str IS NULL OR P_Str = '' THEN
		RETURN 1;
	END IF;
	
	RETURN 0;
END//
DELIMITER ;