DROP FUNCTION IF EXISTS `FN_SEQ`;
DELIMITER //
CREATE FUNCTION `FN_SEQ`(`P_Name` VARCHAR(20)) RETURNS int(11)
	READS SQL DATA
    SQL SECURITY INVOKER
    NOT DETERMINISTIC
 BEGIN
     SET @tmp_seq=1;
     INSERT INTO sys_sequence(`name`,`val`) VALUES(P_Name, 1) ON DUPLICATE KEY UPDATE val=(@tmp_seq:=(val+1));
     RETURN @tmp_seq;
END//
DELIMITER ;