DROP PROCEDURE IF EXISTS `I_DL_TMP_GIFT_TRADE_ORDER`;
DELIMITER //
CREATE PROCEDURE `I_DL_TMP_GIFT_TRADE_ORDER`()
    SQL SECURITY INVOKER
	COMMENT '新建订单货品插入的临时表,为赠品准备'
MAIN_LABEL:BEGIN
	CREATE TEMPORARY TABLE IF NOT EXISTS tmp_gift_trade_order(
	  rec_id INT(11) NOT NULL AUTO_INCREMENT,
	  is_suite INT(11) NOT NULL,
	  spec_id INT(11) NOT NULL,
	  num DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
	  discount DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
	  amount DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
	  weight DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
	  class_path VARCHAR(1024) NOT NULL,
	  brand_id INT(11) NOT NULL,
	  from_mask INT(11) NOT NULL,
	  PRIMARY KEY (rec_id),
	  UNIQUE INDEX UK_tmp_gift_trade_order (is_suite, spec_id)
	);
END//
DELIMITER ;