DROP PROCEDURE IF EXISTS `I_DL_TMP_SALES_TRADE_ORDER_WAREHOUSE`;
DELIMITER //
CREATE PROCEDURE `I_DL_TMP_SALES_TRADE_ORDER_WAREHOUSE`()
    SQL SECURITY INVOKER
    COMMENT '创建临时表用来存储仓库和对应的货品'
MAIN_LABEL: BEGIN 
		CREATE TEMPORARY TABLE IF NOT EXISTS tmp_sales_trade_order_warehouse(
	  rec_id INT(11) NOT NULL DEFAULT 0,
	  spec_id INT(11) NOT NULL,
	  gift_type INT(11) NOT NULL DEFAULT 0,
	  warehouse_id INT(11) NOT NULL,
	  warehouse_type INT(11) NOT NULL ,
	  large_type INT(11) NOT NULL DEFAULT 0,
	  PRIMARY KEY (rec_id)
	);
END//
DELIMITER ;