DROP PROCEDURE IF EXISTS `SP_INT_ARR_TO_TBL`;
DELIMITER //
CREATE PROCEDURE `SP_INT_ARR_TO_TBL`(IN `P_Str` VARCHAR(8192), IN `P_Clear` INT)
    SQL SECURITY INVOKER
    COMMENT '将字符串数组插入到临时表，如1,2,4,2'
MAIN_LABEL:BEGIN
	DECLARE V_I1, V_I2, V_I3 BIGINT;
	DECLARE V_IT VARCHAR(255);
	
	CREATE TEMPORARY TABLE IF NOT EXISTS tmp_xchg(
		rec_id int(11) NOT NULL AUTO_INCREMENT,
		f1 VARCHAR(40),
		f2 VARCHAR(1024),
		f3 VARCHAR(40),
		PRIMARY KEY (rec_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	IF P_Str IS NULL OR LENGTH(P_Str)=0 THEN
		LEAVE MAIN_LABEL;
	END IF;
	
	IF P_Clear THEN
		DELETE FROM tmp_xchg;
	END IF;
	
	IF P_Str=' ' THEN
		LEAVE MAIN_LABEL;
	END IF;
	
	SET V_I1 = 1;
	STR_LABEL:LOOP
	 SET V_I2 = locate(',', P_Str, V_I1);
	 IF V_I2 = 0 THEN
	   SET V_IT = substring(P_Str, V_I1);
	 ELSE
	   SET V_IT = substring(P_Str, V_I1, V_I2 - V_I1);
	 END IF;
	 
	 IF V_IT IS NOT NULL THEN
		set V_I3 = cast(V_IT as signed);
		INSERT INTO tmp_xchg(f1) VALUES(V_I3);
	 END IF;
	 
	 IF V_I2 = 0 OR V_I2 IS NULL THEN
	   LEAVE STR_LABEL;
	 END IF;
	
	 SET V_I1 = V_I2 + 1;
	END LOOP;
	
END//
DELIMITER ;