DROP PROCEDURE IF EXISTS `SP_UTILS_GET_CFG_CHAR`;
DELIMITER //
CREATE PROCEDURE `SP_UTILS_GET_CFG_CHAR`(IN `P_Key` VARCHAR(60), OUT `P_Val` VARCHAR(256), IN `P_Def` VARCHAR(256))
    SQL SECURITY INVOKER
    COMMENT '读配置'
BEGIN
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET P_Val = P_Def;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION SET P_Val = P_Def;
	
	SELECT `value` INTO P_Val FROM cfg_setting WHERE `key`=P_Key LOCK IN SHARE MODE;
	IF P_Val IS NULL THEN
		SET P_Val = P_Def;
	END IF;
END//
DELIMITER ;