<?php
return array(
    //仓库类别
    'warehouse_type' => array(
		array("status_id" => "1", "name" => "普通仓库"),
		array("status_id" => "2", "name" => "物流宝"),
		array("status_id" => "3", "name" => "京东仓储"),
		array("status_id" => "127", "name" => "其他仓库"),
	),
	//赠品规则类型-用于rule_type 二进制计算
	'gift_rule_type'=>array(
			'shop_list'=>4,
			'time_type'=>3,
			'goods_count'=>7,
			'specify_count'=>9,
			'goods_amount'=>15,
			'receivable'=>16,
			'specify_amount'=>21,
			'specify_multiple'=>12,
			'goods_name_keyword'=>29,
			'csremark_keyword'=>30,
	),
	//赠品规则名称-用于日志记录
	'gift_rule_type_name'=>array(
			'店铺'=>4,
			'策略有效期'=>3,
			'货品总数'=>7,
			'指定货品数量'=>9,
			'货款'=>15,
			'订单实收金额'=>16,
			'指定货品金额'=>21,
			'指定货品倍赠'=>12,
			'宝贝名称关键词'=>29,
			'客服备注关键词'=>30,
	),
	//系统设置名称-用于日志记录
	'system_setting'=>array(
			'login_check_code'						=>'开启登录短信安全验证',
			'change_password_check_code'			=>'开启密码修改短信验证',
			'cfg_open_message_strategy'				=>'启用短信发送策略',
			'crm_member_send_sms_limit_time'		=>'几分钟内只能发送一次',
			'show_number_to_star'					=>'手机号码显示成星号',
			'sys_goods_match_concat_code'			=>'多规格货品匹配使用“主商家编码”+“规格商家编码”方式',
			'sales_trade_trace_operator'			=>'订单全链路同步操作员昵称',
			'sales_trade_trace_enable'				=>'开启订单全链路',
			'order_auto_download'					=>'自动下载订单',
			'order_auto_downloadjdsellback'			=>'自动下载京东售后单',
			'order_auto_submit'						=>'自动递交原始单',
			'apigoods_auto_match'					=>'递交自动匹配货品（对新增和变化的平台货品进行自动匹配）',
			'order_deliver_auto_merge'				=>'自动合并订单',
			'order_auto_merge_mode'					=>'订单自动合并方式',
			'order_deliver_auto_merge_ban_refund'	=>'禁止申请退款单自动合并',
			'sales_trade_auto_merge_gift'			=>'自动合并重新计算赠品',	
			'order_deliver_auto_exchange'			=>'平台换货自动更换订单货品',
			'refund_should_deliver'					=>'自动递交类型为退款的原始退款单',
			'sales_raw_count_exclude_gift'			=>'订单中原始货品数量不包含赠品',
			'logistics_auto_sync'					=>'启用自动物流同步',
			'order_logistics_sync_time'				=>'物流同步时间',
			'goods_auto_download'					=>'启用淘宝货品自动下载',
			'point_number'							=>'库存数量显示小数点位数',	
			'order_deliver_block_consign'			=>'拦截平台已发货订单',
			'prevent_online_block_consign_stockout'	=>'不阻止确认发货',
			'cfg_login_interval'                   	=>'用户登录时间间隔',
			'logistics_disabled_search'           	=>'停用的物流不在搜索下拉列表中显示',
			'shop_disabled_search'                 	=>'停用的店铺不在搜索下拉列表中显示',
			'reason_disabled_search'               	=>'停用的原因列表不在搜索下拉列表中显示',
			'warehouse_disabled_search'				=>'停用的仓库不在搜索下拉列表中显示',
			
			'order_check_warn_has_unmerge'			=>'拦截同名未合并订单（开启同名未合并订单标记）',
			'order_check_warn_has_unmerge_checked'	=>'同名未合并（包含已审核订单）',
			'order_check_warn_has_unmerge_freeze'	=>'同名未合并（包含冻结）',
			'order_check_warn_has_unmerge_address'	=>'同名未合并（包含不同地址）',			
			'order_check_warn_has_unpay'			=>'提示有未付款的同名未合并订单',
			'order_check_no_stock'					=>'阻止库存不足订单通过审核',
			'order_check_black_customer'			=>'阻止黑名单客户通过审核',
		//	'order_check_get_waybill'				=>'订单审核自动获取电子面单',
			'order_limit_real_price'				=>'限制手工建单商品折后价',	
			'real_price_limit_value'				=>'手工建单商品折后价的限制值',
			'order_allow_man_create_cod'			=>'允许手工新建COD（货到付款）订单',	
			'sales_trade_split_num'					=>'允许拆分数量为小数',
			'order_allow_part_sync'					=>'开启淘宝拆单发货',
			'order_cal_weight_by_suite'				=>'订单包含组合装时按照组合装重量计算订单重量',
			'order_check_force_check_pwd_is_open'	=>'开启强制审核校验密码',
			'order_check_force_check_pwd'			=>'强制审核密码',
			'return_agree_auto_sync_remark'			=>'同意换货单后自动同步备注',
			'return_agree_auto_remark'				=>'同意换货单后同步的备注',
			'goods_match_split_char'				=>'平台货品匹配截取字符',
			'order_sync_interval'					=>'下载订单时间间隔',			
			'order_go_preorder'						=>'开启预订单',
			'order_preorder_lack_stock'				=>'库存不足转预订单',
			'auto_check_is_open'					=>'开启自动审核',
			'auto_check_buyer_message'				=>'自动审核无客户备注',	
			'auto_check_csremark'					=>'自动审核无客服备注',
			'auto_check_no_invoice'					=>'自动审核无发票',
			'auto_check_no_adr'						=>'自动审核收货地址无（村、组）',
			'auto_check_under_weight'				=>'自动审核订单重量低于（≤）',
			'auto_check_max_weight'					=>'自动审核限重',
			'auto_check_time_type'					=>'自动审核时间类型',
			'auto_check_start_time'					=>'自动审核下单开始时间',			
			'auto_check_end_time'					=>'自动审核下单结束时间',
			'order_fa_condition'					=>'开启财务审核',
			'order_fc_man_order'					=>'手工建单进财务审核',
			'order_fc_excel_import'					=>'EXCEL导入订单进财务审核',
			'order_fc_gift'							=>'订单全是赠品进财审',
			'order_fc_receivable_outnumber'			=>'订单应收金额高于 ',
			'order_fc_discount'						=>'优惠金额达到',
			'order_fc_below_costprice'				=>'订单中商品成交金额低于成本价时进财审',
            'specname_goodsname_allow_update'       =>'允许更新单品及货品名',
			'stockout_examine_goods'				=>'销售出库必须验货',
			'stockout_weight_goods'					=>'销售出库必须称重',
			'stockout_examine_auto_consign'			=>'验货后自动发货',
			'stockout_weight_auto_consign'			=>'称重后自动发货',
			'overflow_weight_alarm'					=>'开启“称重重量-预估重量”超额提示',
			'overflow_weight_small'					=>'称重重量-预估重量最小值',
			'overflow_weight_big'					=>'称重重量-预估重量最大值',
			'purchase_alarmstock_open'				=>'开启库存预警',
			'purchase_auto_alarmstock'				=>'自动刷新警戒库存',
			'stock_auto_sync'						=>'启用库存同步',
			'spec_stocksyn_priority'				=>'单品库存同步策略优先级高于全局库存同步策略',
			'order_check_no_stock_stockout'			=>'阻止库存不足负库存出库',
			'stockout_sendbill_print_status'		=>'显示已打印发货单',
			'stockout_logistics_print_status'		=>'显示已打印物流单',
			'stockout_consign_disable_revert'		=>'发货后禁止撤销发货',
			'stock_scan_once'						=>'包裹扫描一次称重(不勾选则扫描2次)',
			'stock_auto_submit_time'				=>'包裹扫描一次称重多少秒后自动提交',
			'share_post_fee_to_cost_price'			=>'入库时将邮费(包括其他费用)均摊到成本价',
			'sys_available_stock'					=>'可发库存的计算方式',
			'sys_available_purchase'				=>'每日预警采购量计算方式',
			'sales_print_time_range'				=>'单据打印默认显示订单的时间段',
			'syncLogistics_examine_goods'			=>'预物流同步必须验货',
			'syncLogistics_check_weight'			=>'预物流同步必须称重',
			'stockin_auto_commit'					=>'入库开启自动提交',
			'stockout_auto_commit'					=>'出库开启自动提交',
			'stocktransfer_auto_commit'				=>'调拨开启自动提交',
			'stockinventory_auto_commit'			=>'盘点开启自动提交',
			'dynamic_allocation_box'				=>'切换动态分拣框',
			'return_order_auto_sync_remark'			=>'同意退货单后自动同步备注',
			'return_order_auto_remark'				=>'同意退货单后同步的备注',
			'cancel_sorting_order_auto_stockout'	=>'档口单取消订单（取消、全额退款、删除、清除）后，已分拣入库货品自动完成出库',
	)
);
