<?php  
namespace Purchase\Field;
use Common\Common\Field;
use Common\Common\UtilDB;
class PurchaseOrderField extends Field{
	
	protected function get($key){
		$fields = array(
			'purchaseorder' =>array(
				'id' => array('field' => 'id', 'hidden' => true),
				'商家编码'=>array('field'=>'spec_no','width'=>'100'),
				'货品编号'=>array('field'=>'goods_no','width'=>'100'),
				'货品名称' => array('field' => 'goods_name', 'width' => '100'),
                '货品图片'=>array('field' => 'img_url', 'width' => '100','formatter'=>'formatter.print_img'),
				'规格名称' => array('field' => 'spec_name', 'width' => '100'),
                '规格码' => array('field' => 'spec_code', 'width' => '100'),
                '条形码' => array('field' => 'barcode', 'width' => '100'),
				'品牌id' => array('field' => 'brand_id', 'width' => '100','hidden'=>true),
                '品牌' => array('field' => 'brand_name', 'width' => '100'),
				'基本单位'=>array('field'=>'unit_name','width'=>'100'),
				'库存量'=>array('field'=>'stock_num','width'=>'50'),
				'采购量(可编辑)'=>array('field'=>'num','width'=>'100','editor'=>'{type:"numberbox",options:{required:true,precision:'.get_config_value('point_number',0).',value:0,min:0}}'),
				'零售价(可编辑)' =>array('field' => 'price', 'width' => '100','methods'=>'editor:{type:"numberbox",options:{required:true,precision:4,min:0}}'),
				'折扣率(可编辑)' =>array('field' => 'discount_rate', 'width' => '100','methods'=>'editor:{type:"numberbox",options:{required:true,precision:4,min:0}}'),
				'采购价(可编辑)' =>array('field' => 'cost_price', 'width' => '100','methods'=>'editor:{type:"numberbox",options:{required:true,precision:4,min:0}}'),
				'采购总金额' =>array('field' => 'amount', 'width' => '100'),
			
				//'备注' =>array('field'=>'remark','width'=>'100','methods'=>'editor:{type:"textbox"}'),
				'备注(可编辑)'=>array('field'=>'remark','width'=>'100','methods'=>'editor:{type:"textbox"}'),
			),
			'purchasemanagement'=>array(
				'id' => array('field' => 'id', 'hidden' => true),
				'采购单号'=>array('field' => 'purchase_no', 'width'=>'150','align' => 'center'),
				'供应商'=>array('field'=>'provider_name','width'=>'100','align' => 'center'),
				'采购状态'=>array('field'=>'status','width'=>'100','align' => 'center','formatter' => 'formatter.purchase_status',),
				'收货仓库' => array('field' => 'warehouse_name', 'width' => '150','align' => 'center'),
				'外部WMS单号' => array('field' => 'outer_no', 'width' => '150','align' => 'center'),
				'WMS错误信息' => array('field' => 'error_info', 'width' => '150','align' => 'center'),
                '建单人' => array('field' => 'creator_name', 'width' => '100','align' => 'center'),
                '采购员' => array('field' => 'purchaser_name', 'width' => '100','align' => 'center'),
                '物流方式' => array('field' => 'logistics_type', 'width' => '150','align' => 'center'),
				'货品总价' => array('field' => 'goods_fee', 'width' => '100','align' => 'center'),
                '邮费' => array('field' => 'post_fee', 'width' => '100','align' => 'center'),
                '其他费用' => array('field' => 'other_fee', 'width' => '100','align' => 'center'),
                '总金额' => array('field' => 'tax_fee', 'width' => '100','align' => 'center'),
				'货品类别' => array('field' => 'goods_type_count', 'width' => '100','align' => 'center'),
				'货品数量' => array('field' => 'goods_count', 'width' => '100','align' => 'center'),
				'备注' => array('field' => 'remark', 'width' => '100','align' => 'center'),
				'修改时间' => array('field' => 'modified', 'width' => '150','align' => 'center'),
				'创建时间' => array('field' => 'created', 'width' => '150','align' => 'center'),
			),
			'purchase_order_detail'=>array(
				'id' => array('field' => 'id', 'hidden' => true),
				'商家编码' => array('field' => 'spec_no', 'width' => '100'),
                '货品编号' => array('field' => 'goods_no', 'width' => '100'),
                '货品名称' => array('field' => 'goods_name', 'width' => '100'),
                //'货位' => array('field' => 'position_no', 'width' => '100'),
                '规格码' => array('field' => 'spec_code', 'width' => '100'),
                '规格名称' => array('field' => 'spec_name', 'width' => '100'),
                '条形码' => array('field' => 'barcode', 'width' => '100'),
				'到货量' =>array('field' => 'arrive_num','width' => '100'),
				'停止采购数量' =>array('field' => 'stop_num','width' => '100'),
				'品牌id'=>array('field'=>'brand_id','width'=>'100','hidden'=>true),
                '品牌'=>array('field'=>'brand_name','width'=>'100'),
				'基本单位' => array('field' => 'unit_name', 'width' => '100'),               
			    '库存量'=>array('field'=>'stock_num','width'=>'100'),
				'采购量' => array('field' => 'num', 'width' => '100'),
				'折扣率' => array('field' => 'discount', 'width' => '100'),
				'采购价' => array('field' => 'cost_price', 'width' => '100'),
                '采购金额' => array('field' => 'amount', 'width' => '100'),
                '备注' => array('field' => 'remark', 'width' => '100'),
			),
			'purchase_order_log'=>array(
				'id' => array('field' => 'id', 'hidden' => true),
				'操作员' => array('field' => 'account', 'width' => '100'),
                '操作' => array('field' => 'remark', 'width' => '800'),
                '时间' => array('field' => 'created', 'width' => '150'),
                
			),
			'purchase_order_export'=>array(
				'采购单号'=>array('field' => 'purchase_no', 'width'=>'150','align' => 'center'),
				'供应商'=>array('field'=>'provider_name','width'=>'100','align' => 'center'),
				'采购状态'=>array('field'=>'status','width'=>'100','align' => 'center','formatter' => 'formatter.purchase_status',),
				'收货仓库' => array('field' => 'warehouse_name', 'width' => '150','align' => 'center'),
				'建单人' => array('field' => 'creator_name', 'width' => '100','align' => 'center'),
				'采购员' => array('field' => 'purchaser_name', 'width' => '100','align' => 'center'),
				'商家编码' => array('field' => 'spec_no', 'width' => '100'),
				'货品编号' => array('field' => 'goods_no', 'width' => '100'),
				'货品名称' => array('field' => 'goods_name', 'width' => '100'),
				'规格码' => array('field' => 'spec_code', 'width' => '100'),
				'规格名称' => array('field' => 'spec_name', 'width' => '100'),
				'条形码' => array('field' => 'barcode', 'width' => '100'),
				'到货量' =>array('field' => 'arrive_num','width' => '100'),
				'停止采购数量' =>array('field' => 'stop_num','width' => '100'),
				'品牌'=>array('field'=>'brand_name','width'=>'100'),
				'基本单位' => array('field' => 'unit_name', 'width' => '100'),
				'库存量'=>array('field'=>'stock_num','width'=>'100'),
				'采购量' => array('field' => 'num', 'width' => '100'),
				'折扣率' => array('field' => 'discount', 'width' => '100'),
				'采购价' => array('field' => 'cost_price', 'width' => '100'),
				'采购金额' => array('field' => 'amount', 'width' => '100'),
				'备注' => array('field' => 'remark', 'width' => '100'),
				'修改时间' => array('field' => 'modified', 'width' => '150','align' => 'center'),
				'创建时间' => array('field' => 'created', 'width' => '150','align' => 'center'),
			),
		);
		 return $fields[$key];
	}
	
}