<?php
namespace Trade\Field;
use Common\Common\Field;
class TradeDetailField extends Field{

    protected function get($key){
    	$fields = array(
    			'trade_detail'=> array(
    					'id'     => array('field'=>'id','hidden'=>true),
    					'flag_id'=> array('field'=>'flag_id','hidden'=>true),
						'checkbox'=>array('field'=>'ck','hidden'=>false,'checkbox'=>true,'frozen'=>true),
    					'订单号'   => array('field'=>'trade_no','width'=>100),
    					'店铺名称'  => array('field'=>'shop_name','width'=>100),
    					'原始单号'  => array('field'=>'src_tids','width'=>100),
    					'客户网名'   => array('field'=>'buyer_nick','width'=>100),
    					'收件人'  => array('field'=>'receiver_name','width'=>100),
    					'地区'  => array('field'=>'receiver_area','width'=>150),
    					'地址'  => array('field'=>'receiver_address','width'=>150),
    					'手机'  => array('field'=>'receiver_mobile','width'=>100),
    					'固话'  => array('field'=>'receiver_telno','width'=>100),
    					'邮编'  => array('field'=>'receiver_zip','width'=>100),
    					'发货条件'  => array('field'=>'delivery_term','width'=>100,'formatter'=>'formatter.delivery_term'),
    					'订单状态'  => array('field'=>'trade_status','width'=>100,'formatter'=>'formatter.trade_status'),
    					'退货状态'  => array('field'=>'order_refund_status','width'=>100,'formatter'=>'formatter.order_refund_status'),
    					'仓库'  => array('field'=>'warehouse_name','width'=>100),
    					'物流公司'  => array('field'=>'logistics_id','width'=>100),
    					'物流单号'  => array('field'=>'logistics_no','width'=>100),
    					'客服备注'  => array('field'=>'cs_remark','width'=>100),
    					'买家留言'  => array('field'=>'buyer_message','width'=>100),
    					'商家编码' => array('field'=>'spec_no','width'=>100),
    					'货品编号' => array('field'=>'goods_no','width'=>100),
    					'货品名称' => array('field'=>'goods_name','width'=>100),
    					'规格名称' => array('field'=>'spec_name','width'=>100),
                        '规格码'   => array('field'=>'spec_code','width'=>100),
    					'平台货品名称' => array('field'=>'api_goods_name','width'=>100),
    					'平台规格名称' => array('field'=>'api_spec_name','width'=>100),
    					'下单数量' => array('field'=>'num','width'=>100),
    					'实发数量' => array('field'=>'actual_num','width'=>100),
    					'标价' => array('field'=>'price','width'=>100),
    					'优惠' => array('field'=>'order_discount','width'=>100),
    					'成交价' => array('field'=>'order_price','width'=>100),
						'成本价'=>array('field'=>'cost_price','width'=>80),
    					'打折比' => array('field'=>'discount_rate','width'=>100),
    					'分摊后单价' => array('field'=>'share_price','width'=>100),
    					'分摊后总价' => array('field'=>'share_amount','width'=>100),
    					'分摊邮资' => array('field'=>'share_post','width'=>100),
    					'单品支付金额'=> array('field'=>'order_paid','width'=>100),
    					'拆自组合装' => array('field'=>'suite_name','width'=>100),
    					'估重' => array('field'=>'order_weight','width'=>100),
    					'订单总邮费'  => array('field'=>'post_amount','width'=>100),
    					'订单总折扣'  => array('field'=>'discount','width'=>100),
    					'订单总应收'  => array('field'=>'receivable','width'=>100),
    					'订单总支付金额'  => array('field'=>'paid','width'=>100),
    					'货到付款金额'  => array('field'=>'dap_amount','width'=>100),
    					'买家COD费用'  => array('field'=>'cod_amount','width'=>100),
    					'预估邮资成本'  => array('field'=>'post_cost','width'=>100),
    					'货品估算成本'  => array('field'=>'goods_cost','width'=>100),
    					'订单预估总重量'  => array('field'=>'weight','width'=>100),
    					'需要发票'  => array('field'=>'invoice_type','width'=>100,'formatter'=>'formatter.invoice_type'),
    					'发票抬头'  => array('field'=>'invoice_title','width'=>100),
    					'发票内容'  => array('field'=>'invoice_content','width'=>100),
    					'下单时间'  => array('field'=>'trade_time','width'=>100),
    					'支付账户'  => array('field'=>'pay_account','width'=>100),
    					'业务员'  => array('field'=>'salesman_id','width'=>100),
    					'审核人'  => array('field'=>'checker_id','width'=>100),
                        //'财审人'  => array('field'=>'fchecker_id','width'=>100),
    					'打印备注'  => array('field'=>'print_remark','width'=>100),
    					'备注'  => array('field'=>'remark','width'=>100),
    					'订单类型'  => array('field'=>'trade_type','width'=>100,'formatter'=>'formatter.trade_type'),
    					'订单来源'  => array('field'=>'trade_from','width'=>100,'formatter'=>'formatter.trade_from'),
                        '佣金' => array('field'=>'commission','width'=>100),
                        '赠品方式' => array('field'=>'gift_type','width'=>100,'formatter'=>'formatter.gift_type'),
                        '证件号码' => array('field'=>'id_card','width'=>100),
    			),
    			'shop_list'=>array(
    					'id'     => array('field'=>'id','hidden'=>true),
    					'店铺名称'  => array('field'=>'shop_name','width'=>150),
    					'平台'  	 => array('field'=>'platform_id','width'=>100,'formatter'=>'formatter.platform_id'),
    					'子平台'   => array('field'=>'sub_platform_id','width'=>100,'formatter'=>'formatterSubPlatForm'),
    					'平台账号'  => array('field'=>'account_nick','width'=>150),
    					'授权状态'  => array('field'=>'auth_state','width'=>100,'formatter'=>'formatter.auth_state'),
    			),
    	);
    	return $fields[$key];
    }
}