<?php
namespace Trade\Field;

use Common\Common\Field;
class TradeCheckField extends Field{

	protected function get($key){
		$point_number = get_config_value('point_number',0);
		if($key=='split_main_trade' ||$key=='split_common_order')
		{//订单拆分-拆分数是否可以为小数   0-只能整数  1-可以为小数    默认为0
			$res_cfg_val=get_config_value('sales_trade_split_num');
			$split_main_trade_editor=$res_cfg_val==0?'editor:"numberbox"':'editor:{type:"numberbox",options:{precision:'.$point_number.'}}';
		}
		$fields = array(
				'trade_check'=>array(
						'id'     => array('field'=>'id','hidden'=>true,'sortable'=>true),
						'flag_id'=> array('field'=>'flag_id','hidden'=>true,'sortable'=>true),
						'checkbox'=>array('field'=>'ck','hidden'=>false,'checkbox'=>true,'frozen'=>true),
						'系统标记'=>array('field'=>'flag','width'=>100,'frozen'=>true),
						'订单号'   => array('field'=>'trade_no','width'=>100,'sortable'=>true),
						'店铺名称'  => array('field'=>'shop_id','width'=>100,'sortable'=>true),
						'原始单号'  => array('field'=>'src_tids','width'=>150,'sortable'=>true),
						'客户网名'   => array('field'=>'buyer_nick','width'=>100,'sortable'=>true),
						'收件人'  => array('field'=>'receiver_name','width'=>80,'sortable'=>true),
						'地区'  => array('field'=>'receiver_area','width'=>150,'sortable'=>true),
						'地址'  => array('field'=>'receiver_address','width'=>150,'sortable'=>true),
						'手机'  => array('field'=>'receiver_mobile','width'=>100,'sortable'=>true),
						'客服备注'  => array('field'=>'cs_remark','width'=>100,'sortable'=>true),
						'买家留言'  => array('field'=>'buyer_message','width'=>100,'sortable'=>true),
						'货品总量'  => array('field'=>'goods_count','width'=>100,'sortable'=>true),
						'总货款'  => array('field'=>'goods_amount','width'=>100,'sortable'=>true),
						'固话'  => array('field'=>'receiver_telno','width'=>100,'sortable'=>true),
						'邮编'  => array('field'=>'receiver_zip','width'=>100,'sortable'=>true),
						'发货条件'  => array('field'=>'delivery_term','width'=>100,'sortable'=>true,'formatter'=>'formatter.delivery_term'),
						'订单状态'  => array('field'=>'trade_status','width'=>100,'sortable'=>true,'formatter'=>'formatter.trade_status'),
						'退货状态'  => array('field'=>'refund_status','width'=>100,'sortable'=>true,'formatter'=>'formatter.refund_status'),
						'仓库'  => array('field'=>'warehouse_name','width'=>100,'sortable'=>true),
						'物流公司'  => array('field'=>'logistics_id','width'=>100,'sortable'=>true),
						'打印备注'  => array('field'=>'print_remark','width'=>100,'sortable'=>true),
						'货品种类数'  => array('field'=>'goods_type_count','width'=>100,'sortable'=>true),
						'邮费'  => array('field'=>'post_amount','width'=>100,'sortable'=>true),
						'优惠'  => array('field'=>'discount','width'=>100,'sortable'=>true),
						'应收'  => array('field'=>'receivable','width'=>100,'sortable'=>true),
						'已付'  => array('field'=>'paid','width'=>100,'sortable'=>true),
						'款到发货金额'  => array('field'=>'dap_amount','width'=>100,'sortable'=>true),
						'买家COD费用'  => array('field'=>'cod_amount','width'=>100,'sortable'=>true),
						//'佣金'  => array('field'=>'commission','width'=>100,'sortable'=>true),
						'预估邮资成本'  => array('field'=>'post_cost','width'=>100,'sortable'=>true),
						'货品估算成本'  => array('field'=>'goods_cost','width'=>100,'sortable'=>true),
						'估重'  => array('field'=>'weight','width'=>100,'sortable'=>true),
						'需要发票'  => array('field'=>'invoice_type','width'=>100,'sortable'=>true,'formatter'=>'formatter.invoice_type'),
						'发票抬头'  => array('field'=>'invoice_title','width'=>100,'sortable'=>true),
						'发票内容'  => array('field'=>'invoice_content','width'=>100,'sortable'=>true),
						'下单时间'  => array('field'=>'trade_time','width'=>100,'sortable'=>true),
						'付款时间'  => array('field'=>'pay_time','width'=>100,'sortable'=>true),
						'支付账户'  => array('field'=>'pay_account','width'=>100,'sortable'=>true),
						'送货时间'  => array('field'=>'to_deliver_time','width'=>100,'sortable'=>true),
						'业务员'  => array('field'=>'salesman_id','width'=>100,'sortable'=>true),
						'类型'  => array('field'=>'trade_type','width'=>100,'sortable'=>true,'formatter'=>'formatter.trade_type'),
						'处理天数'  => array('field'=>'handle_days','width'=>100,'sortable'=>true),
						'订单来源'  => array('field'=>'trade_from','width'=>100,'sortable'=>true,'formatter'=>'formatter.trade_from'),
						'货品摘要'  => array('field'=>'single_spec_no','width'=>100,'sortable'=>true),
						'原始货品种类'  => array('field'=>'raw_goods_type_count','width'=>100,'sortable'=>true),
						'原始货品数量'  => array('field'=>'raw_goods_count','width'=>100,'sortable'=>true),
						'标记名称'  => array('field'=>'flag_name','width'=>100,'sortable'=>true),
						'标旗'	=> array('field'=>'remark_flag','width'=>60,'sortable'=>true),
						'递交时间'  => array('field'=>'created','width'=>100,'sortable'=>true),
				),
				'invalid_goods'=>array(
						'id' => array('field'=>'id','hidden'=>true,'sortable'=>true),
						'ags_id' => array('field'=>'ags_id','hidden'=>true,'sortable'=>true),
						'原因' => array('field'=>'reason','width'=>100),
						'店铺' => array('field'=>'shop_id','width'=>100),
						'商家编码'  => array('field'=>'merchant_no','width'=>100),
						'平台货品编码'  => array('field'=>'goods_no','width'=>100),
						'平台规格编码'  => array('field'=>'spec_no','width'=>100),
						'规格码'  => array('field'=>'spec_code','width'=>100),
						'货品名称' 	 => array('field'=>'goods_name','width'=>150),
						'规格名称' 	 => array('field'=>'spec_name','width'=>100),
						'平台货品ID' => array('field'=>'goods_id','width'=>100),
						'平台规格ID' 	 => array('field'=>'spec_id','width'=>100),//递交时间
				),
				'split_main_trade'=>array(
						'id'=>array('field'=>'id','hidden'=>true),
						'拆分数（可编辑）'=>array('field'=>'split_num','width'=>100,'methods'=>$split_main_trade_editor),
						'剩余数量'=>array('field'=>'left_num','width'=>100),
						'子订单编号'=>array('field'=>'src_oid','width'=>100),
						'商家编码'=>array('field'=>'spec_no','width'=>150),
						'货品名称'=>array('field'=>'goods_name','width'=>100),
						'平台货品名称'=> array('field'=>'api_goods_name','width'=>100),
						'平台规格名'=>array('field'=>'api_spec_name','width'=>100),
						'规格'=>array('field'=>'spec_name','width'=>100),
						'数量'=>array('field'=>'num','width'=>100),
						'单价'=>array('field'=>'price','width'=>100),
						'成交价'=>array('field'=>'order_price','width'=>100),
						'调整后价格'=>array('field'=>'share_price','width'=>100),
						'分摊邮费'=>array('field'=>'share_post','width'=>100),
						'优惠金额'=>array('field'=>'discount','width'=>100),
						'金额'=>array('field'=>'share_amount','width'=>100),
						'备注'=>array('field'=>'remark','width'=>100),
						'可发库存'=>array('field'=>'available_stock','width'=>100),
						'预估重量'=>array('field'=>'weight','width'=>100),
				),
				'split_new_trade'=>array(
						'id'=>array('field'=>'id','hidden'=>true,'sortable'=>true),
						'编号'=>array('field'=>'spec_no','width'=>100),
						'货品名称'=>array('field'=>'goods_name','width'=>100),
						'规格'=>array('field'=>'spec_name','width'=>100),
						'数量'=>array('field'=>'num','width'=>100),
						'单价'=>array('field'=>'price','width'=>100),
						'成交价'=>array('field'=>'order_price','width'=>100),
						'调整后价格'=>array('field'=>'share_price','width'=>100),
						'分摊邮费'=>array('field'=>'share_post','width'=>100),
						'优惠金额'=>array('field'=>'discount','width'=>100),
						'金额'=>array('field'=>'share_amount','width'=>100),
						'备注'=>array('field'=>'remark','width'=>100),
				),
				'edit'=>array(//sales_trade_modify_order
						'id'=>array('field'=>'id','hidden'=>true),
						'平台'=>array('field'=>'platform_id','width'=>60,'formatter'=>'formatter.platform_id'),
						'货品名称'=>array('field'=>'goods_name','width'=>150),
// 						'规格名'=>array('field'=>'spec_name','width'=>100),//,'methods'=>'editor:{type:"textbox"}'
						'规格名（可编辑）'=>array('field'=>'spec_name','width'=>150,'formatter'=>'f_spec','methods'=>'editor:{type:"combobox",options:{panelHeight: "100",valueField: "id",textField: "name",data: spec,required: true,checkbox: true,editable: false,onSelect:sel_spec}}'),
						// '原始订单号'=>array('field'=>'src_tids','width'=>100),						
						'商家编号'=>array('field'=>'spec_no','width'=>100),
						'下单数量'=>array('field'=>'num','width'=>80),
						'标价'=>array('field'=>'price','width'=>80),
						'成交价'=>array('field'=>'order_price','width'=>80),
						'实发数量(可编辑)'=>array('field'=>'actual_num','width'=>80,'methods'=>'editor:{type:"numberbox",options:{required:true,precision:'.$point_number.'}}'),
						'备注'=> array('field'=>'remark','width'=>150,'methods'=>'editor:"text"'),
						'成本价'=>array('field'=>'cost_price','width'=>80),	
						// '分摊价格(可编辑)'=>array('field'=>'share_price','width'=>80,'methods'=>'editor:{type:"numberbox",options:{required:true,precision:4}}'),
						// '分摊后总价(可编辑)'=>array('field'=>'share_amount','width'=>80,'methods'=>'editor:{type:"numberbox",options:{required:true,precision:4}}'),
						'优惠后单价(可编辑)'=>array('field'=>'share_price','width'=>80,'methods'=>'editor:{type:"numberbox",options:{required:true,precision:4}}'),
						'优惠后总价(可编辑)'=>array('field'=>'share_amount','width'=>80,'methods'=>'editor:{type:"numberbox",options:{required:true,precision:4}}'),
						'优惠(可编辑)'=>array('field'=>'discount','width'=>80,'methods'=>'editor:{type:"numberbox",options:{required:true,precision:4}}'),
						'分摊邮费(可编辑)'=>array('field'=>'share_post','width'=>80,'methods'=>'editor:{type:"numberbox",options:{required:true,precision:4}}'),
						'赠品方式'=>array('field'=>'gift_type','width'=>60,'formatter'=>'formatter.gift_type'),
						'拆自组合装'=>array('field'=>'suite_name','width'=>80),//拆自组合装
						'组合装数量'=>array('field'=>'suite_num','width'=>80),
						'组合装编码'=>array('field'=>'suite_no','width'=>80),
						'估重'=>array('field'=>'weight','width'=>80),
						'库存'=> array('field'=>'stock_num','width'=>80),
						'子订单编号'=>array('field'=>'src_oid','width'=>100),//
						'货品编号'=>array('field'=>'goods_no','width'=>100),
						'规格码'=>array('field'=>'spec_code','width'=>100),
				),
				'exchange'=>array(
		                'id' => array('field' => 'id', 'hidden'=>'true'),
		                '商家编码' => array('field' => 'spec_no',   'width'=>130),
		                '货品名称' => array('field' => 'goods_name',  'width'=>150),
		                '规格名称' => array('field' => 'spec_name',   'width'=>150),
		                '价格'=>array('field'=>'price','width'=>100),
		                '数量(可编辑)' => array('field' => 'num',   'width'=>100,'methods'=>'editor:{type:"numberbox",options:{required:true,min:1}}'),
	            ),
            	'order'=>array(
						'id'=>array('field'=>'id','hidden'=>true),
						'平台'=>array('field'=>'platform_id','width'=>60,'formatter'=>'formatter.platform_id'),
						'货品名称'=>array('field'=>'goods_name','width'=>150),
						'规格名'=>array('field'=>'spec_name','width'=>100),//,'methods'=>'editor:{type:"textbox"}'
						// '原始订单号'=>array('field'=>'src_tids','width'=>100),
						'子订单编号'=>array('field'=>'src_oid','width'=>100),//
						'商家编号'=>array('field'=>'spec_no','width'=>100),
						'货品编号'=>array('field'=>'goods_no','width'=>100),
						'规格码'=>array('field'=>'spec_code','width'=>100),
						'下单数量'=>array('field'=>'num','width'=>80),
						'成本价'=>array('field'=>'cost_price','width'=>80),
						'标价'=>array('field'=>'price','width'=>80),
						'成交价'=>array('field'=>'order_price','width'=>80),
						'实发数量'=>array('field'=>'actual_num','width'=>80),
						'分摊价格'=>array('field'=>'share_price','width'=>80),
						'分摊后总价'=>array('field'=>'share_amount','width'=>80),
						'分摊邮费'=>array('field'=>'share_post','width'=>80),
						'优惠'=>array('field'=>'discount','width'=>80),
						'赠品方式'=>array('field'=>'gift_type','width'=>60,'formatter'=>'formatter.gift_type'),
						'拆自组合装'=>array('field'=>'suite_name','width'=>80),//拆自组合装
						'组合装数量'=>array('field'=>'suite_num','width'=>80),
						'组合装编码'=>array('field'=>'suite_no','width'=>80),
						'估重'=>array('field'=>'weight','width'=>80),
						'库存'=> array('field'=>'stock_num','width'=>80),
						'备注'=> array('field'=>'remark','width'=>150),
				),
				'split_common_order'=>array(
						'id'=>array('field'=>'id','hidden'=>true),
						'拆分数（可编辑）'=>array('field'=>'split_num','width'=>100,'methods'=>$split_main_trade_editor),
						'剩余数量'=>array('field'=>'left_num','width'=>100),
						'商家编码'=>array('field'=>'spec_no','width'=>150),
						'货品名称'=>array('field'=>'goods_name','width'=>100),
						'平台货品名称'=> array('field'=>'api_goods_name','width'=>100),
						'平台规格名'=>array('field'=>'api_spec_name','width'=>100),
						'规格'=>array('field'=>'spec_name','width'=>100),
						'数量'=>array('field'=>'num','width'=>100),
						'单价'=>array('field'=>'price','width'=>100),
						'成交价'=>array('field'=>'order_price','width'=>100),
						'调整后价格'=>array('field'=>'share_price','width'=>100),
						'分摊邮费'=>array('field'=>'share_post','width'=>100),
						'优惠金额'=>array('field'=>'discount','width'=>100),
						'金额'=>array('field'=>'share_amount','width'=>100),
						'备注'=>array('field'=>'remark','width'=>100),
						'可发库存'=>array('field'=>'available_stock','width'=>100),
						'预估重量'=>array('field'=>'weight','width'=>100),
				),
				'consign'=>array(
						'id'=>array('field'=>'id','hidden'=>true),
						'订单号'   => array('field'=>'trade_no','width'=>130,'sortable'=>true),
						'店铺名称'  => array('field'=>'shop_name','width'=>110,'sortable'=>true),
						'收件人'  => array('field'=>'receiver_name','width'=>110,'sortable'=>true),
						'物流公司（可编辑）'=>array('field'=>'logistics_id','width'=>150,'formatter'=>'f_logistics','methods'=>'editor:{type:"combobox",options:{panelHeight: "200",valueField: "id",textField: "name",data: logistics,required: true,checkbox: true,editable: false,onSelect:select_logistics,}}'),
						'物流单号（可编辑）'  => array('field'=>'logistics_no','width'=>200,'methods'=>'editor:{type:"textbox"}'),
				),
				'gift_not_send_reason'=>array(
						'id'=>array('field'=>'rec_id','hidden'=>true),
						'策略编码' => array('field' => 'rule_no',  'sortable' => true, 'width'=>150),
                		'规则名称' => array('field' => 'rule_name',  'sortable' => true, 'width'=>150),
                		'未赠原因' => array('field' => 'reason', 'sortable' => true, 'width'=>300),

				),
				'suite_split'=>array(
						'id'=>array('field'=>'id','hidden'=>true),
						'拆分数（可编辑）'=>array('field'=>'split_num','width'=>100,'methods'=>'editor:{type:"numberbox",options:{required:true,min:0}}'),
						'剩余数量' => array('field' => 'left_num', 'sortable' => true, 'width'=>100),
						'子订单编号'=>array('field'=>'src_oid','width'=>100),
						'组合装商家编码' => array('field' => 'suite_no',  'sortable' => true, 'width'=>100),
                		'组合装名称' => array('field' => 'suite_name',  'sortable' => true, 'width'=>150),                		
                		'货品名称' => array('field' => 'suite_name',  'sortable' => true, 'width'=>150),
						'货品名称'=>array('field'=>'goods_name','width'=>100),
						'平台货品名称'=> array('field'=>'api_goods_name','width'=>100),
						'平台规格名'=>array('field'=>'api_spec_name','width'=>100),
						'数量'=>array('field'=>'num','width'=>100),
				),

		);
		return $fields[$key];
	}
}