<?php
namespace Trade\Field;
use Common\Common\Field;
class TradeCommonField extends Field{

	protected function get($key){
		$fields = array(
				//订单
				'goods_list'=>array(
						'平台'=> array('field'=>'platform_id','width'=>60,'formatter'=>'formatter.platform_id'),
						'图片' => array('field' => 'img_url', 'width' => 60,'formatter'=>'formatter.print_img'),				
						'货品名称'=> array('field'=>'goods_name','width'=>150),
						'规格名'=> array('field'=>'spec_name','width'=>100),
						'商家编号'=> array('field'=>'spec_no','width'=>100),
						'货品编号'=> array('field'=>'goods_no','width'=>100),
						'下单数量'=> array('field'=>'num','width'=>80),
						'成交价'=> array('field'=>'order_price','width'=>100),
						'分摊后总价'=> array('field'=>'share_amount','width'=>100),
						'分摊邮费'=> array('field'=>'share_post','width'=>80),
						'已付'=> array('field'=>'paid','width'=>100),
						'估重'=> array('field'=>'weight','width'=>80),
						'赠品方式'=> array('field'=>'gift_type','width'=>80,'formatter'=>'formatter.gift_type'),
						'原始订单号'=> array('field'=>'src_tid','width'=>100),
						'子订单编号'=> array('field'=>'src_oid','width'=>100),//
						'规格码'=> array('field'=>'spec_code','width'=>100),
						'标价'=> array('field'=>'price','width'=>100),
						'分摊后的价格'=> array('field'=>'share_price','width'=>100),
						'成本价'=> array('field'=>'cost_price','width'=>100),
						'实发数量'=> array('field'=>'actual_num','width'=>100),
						'库存'=> array('field'=>'stock_num_all','width'=>100),
						'可发库存'=> array('field'=>'stock_num','width'=>100),//可审核库存
						//'佣金'=> array('field'=>'commission','width'=>100),
						'拆自组合装'=> array('field'=>'suite_name','width'=>100),//拆自组合装
						'组合装数量'=> array('field'=>'suite_num','width'=>100),
						'组合装编码'=> array('field'=>'suite_no','width'=>100),
						'担保方式'=> array('field'=>'guarantee_mode','width'=>100,'formatter'=>'formatter.guarantee_mode'),
						'退货状态'=> array('field'=>'refund_status','width'=>100,'formatter'=>'formatter.order_refund_status'),
						//'发票'=> array('field'=>'invoice_type','width'=>100,'formatter'=>'formatter.invoice_type'),
						'平台货品名称'=> array('field'=>'api_goods_name','width'=>100),
						'平台规格名'=> array('field'=>'api_spec_name','width'=>100),
						'备注'=> array('field'=>'remark','width'=>100),
						'平台已发货'=> array('field'=>'is_consigned','width'=>100),
				),
				'trade_detail'=>array(
						'name1'=> array('field'=>'name1','width'=>100,'methods'=>'styler:tradeDetailStyler'),
						'value1'=> array('field'=>'value1','width'=>105),
						'name2'=> array('field'=>'name2','width'=>100,'methods'=>'styler:tradeDetailStyler'),
						'value2'=> array('field'=>'value2','width'=>115),
						'name3'=> array('field'=>'name3','width'=>100,'methods'=>'styler:tradeDetailStyler'),
						'value3'=> array('field'=>'value3','width'=>120),
						'name4'=> array('field'=>'name4','width'=>100,'methods'=>'styler:tradeDetailStyler'),
						'value4'=> array('field'=>'value4','width'=>160),
						'name5'=> array('field'=>'name5','width'=>100,'methods'=>'styler:tradeDetailStyler'),
						'value5'=> array('field'=>'value5','width'=>100),
				),
				'src_trade'=>array(//1017-cmd.txt
						'平台'  => array('field'=>'platform_id','width'=>100,'formatter'=>'formatter.platform_id'),
						'店铺'  => array('field'=>'shop_id','width'=>150),
						'原始单号'  => array('field'=>'tid','width'=>150),
						'平台状态'  => array('field'=>'trade_status','width'=>100,'formatter'=>'formatter.api_trade_status'),
						'担保方式'  => array('field'=>'guarantee_mode','width'=>100,'formatter'=>'formatter.guarantee_mode'),
						'支付状态'  => array('field'=>'pay_status','width'=>100,'formatter'=>'formatter.pay_status'),
						'发货条件'  => array('field'=>'delivery_term','width'=>100,'formatter'=>'formatter.delivery_term'),
						'支付方式'  => array('field'=>'pay_method','width'=>100,'formatter'=>'formatter.pay_method'),
						'退款状态'  => array('field'=>'refund_status','width'=>100,'formatter'=>'formatter.refund_status'),
						'系统状态'  => array('field'=>'process_status','width'=>100,'formatter'=>'formatter.process_status'),
						'下单时间'  => array('field'=>'trade_time','width'=>100),
						'支付时间'  => array('field'=>'pay_time','width'=>100),
						'客户网名'  => array('field'=>'buyer_nick','width'=>100),
						'收件人姓名'  => array('field'=>'receiver_name','width'=>100),
						'省市县'  => array('field'=>'receiver_area','width'=>100),
						'区域'  => array('field'=>'receiver_district','width'=>100),
						'收件地址'  => array('field'=>'receiver_address','width'=>100),
						'手机'  => array('field'=>'receiver_mobile','width'=>100),
						'电话'  => array('field'=>'receiver_telno','width'=>100),
						'邮编'  => array('field'=>'receiver_zip','width'=>100),
						'送货时间'  => array('field'=>'to_deliver_time','width'=>100),//送货时间 to_deliver_time
						'买家备注'  => array('field'=>'buyer_message','width'=>100),
						'客服备注' => array('field'=>'remark','width'=>100),
						'标旗' => array('field'=>'remark_flag','width'=>100,'formatter'=>'formatter.remark_flag'),
						'货款' => array('field'=>'goods_amount','width'=>100),
						'邮费' => array('field'=>'post_amount','width'=>100),
						'其他收费' => array('field'=>'other_amount','width'=>100),
						'优惠' => array('field'=>'discount','width'=>100),
						'已付' => array('field'=>'paid','width'=>100),
						'平台费用' => array('field'=>'platform_cost','width'=>100),
						'已收' => array('field'=>'received','width'=>100),
						'应收' => array('field'=>'receivable','width'=>100),
						'款到发货金额' => array('field'=>'dap_amount','width'=>100),
						'货到付款金额' => array('field'=>'cod_amount','width'=>100),
						'退款金额' => array('field'=>'refund_amount','width'=>100),
						'物流方式' => array('field'=>'logistics_type','width'=>100,'formatter'=>'formatter.logistics_type'),
						'发票类别' => array('field'=>'invoice_type','width'=>100,'formatter'=>'formatter.invoice_type'),
						'发票抬头' => array('field'=>'invoice_title','width'=>100),
						'发票内容' => array('field'=>'invoice_content','width'=>100),
						'结束时间' => array('field'=>'end_time','width'=>100),
						//'分销方式' => array('field'=>'fenxiao_type','width'=>100,'formatter'=>'formatter.fenxiao_type'),
						//'分销商ID' => array('field'=>'fenxiao_nick','width'=>100),
						'业务员' => array('field'=>'x_salesman_id','width'=>100),//
						'订单来源' => array('field'=>'trade_from','width'=>100,'formatter'=>'formatter.trade_from'),
						'修改时间' => array('field'=>'modified','width'=>100),
						'创建时间' => array('field'=>'created','width'=>100),
				),
				'stock_list'=>array(
						'商家编码'=> array('field'=>'spec_no','width'=>100),
						'货品名称'=> array('field'=>'goods_name','width'=>150),
						'货品编号'=> array('field'=>'goods_no','width'=>100),
						'货品简称'=> array('field'=>'short_name','width'=>100),
						'规格名称'=> array('field'=>'spec_name','width'=>100),
						'实发数量'=> array('field'=>'actual_num','width'=>100),
						'仓库'=> array('field'=>'warehouse_id','width'=>100),//仓库
						'采购到货量'=> array('field'=>'purchase_arrive_num','width'=>100),//采购到货量
						'库存'=> array('field'=>'stock_num_all','width'=>100),//库存 num
						'可发库存'=> array('field'=>'stock_num','width'=>100),//可发库存
						'待发货量'=> array('field'=>'sending_num','width'=>100),//代发货数量
						'待审核量'=> array('field'=>'order_num','width'=>100),
						'预订单量'=> array('field'=>'subscribe_num','width'=>100),
						'成本价'=> array('field'=>'cost_price','width'=>100),//成本价
						'单品备注'=> array('field'=>'remark','width'=>100),//单品备注  goods_spec->remark 不确定
				),
				'lack_stock_list'=>array(
						'商家编码'=> array('field'=>'spec_no','width'=>100),
						'货品名称'=> array('field'=>'goods_name','width'=>150),
						'货品编号'=> array('field'=>'goods_no','width'=>100),
						'货品简称'=> array('field'=>'short_name','width'=>100),
						'规格名称'=> array('field'=>'spec_name','width'=>100),
						'实发数量'=> array('field'=>'actual_num','width'=>100),
						'仓库'=> array('field'=>'warehouse_id','width'=>100),//仓库
						'采购到货量'=> array('field'=>'purchase_arrive_num','width'=>100),//采购到货量
						'库存'=> array('field'=>'stock_num_all','width'=>100),//库存 num
						'可发库存'=> array('field'=>'stock_num','width'=>100),//可发库存
						'待发货量'=> array('field'=>'sending_num','width'=>100),//代发货数量
						'待审核量'=> array('field'=>'order_num','width'=>100),
						'预订单量'=> array('field'=>'subscribe_num','width'=>100),
						'成本价'=> array('field'=>'cost_price','width'=>100),//成本价
						'单品备注'=> array('field'=>'remark','width'=>100),//单品备注  goods_spec->remark 不确定
				),
				'trade_refund'=>array(
						'退换单号'=> array('field'=>'refund_no','width'=>100),
						'店铺'=> array('field'=>'shop_id','width'=>150),
						'类型'=> array('field'=>'type','width'=>100,'formatter'=>'formatter.refund_type'),
						'建单者'=> array('field'=>'operator_id','width'=>100),
						'平台退货单号'=> array('field'=>'src_no','width'=>100),
						'处理状态'=> array('field'=>'process_status','width'=>100,'formatter'=>'formatter.refund_process_status'),
						'平台状态'=> array('field'=>'status','width'=>100,'formatter'=>'formatter.order_refund_status'),
						'原始订单'=> array('field'=>'tid','width'=>100),
						'系统订单'=> array('field'=>'trade_no','width'=>100),
						'客户网名'=> array('field'=>'buyer_nick','width'=>100),//
						'姓名'=> array('field'=>'return_name','width'=>100),
						'手机号'=> array('field'=>'return_mobile','width'=>100),
						'固话'=> array('field'=>'return_telno','width'=>100),
						'地址'=> array('field'=>'return_address','width'=>100),
						'退货货品数量'=> array('field'=>'refund_num','width'=>100),//退货货品数量
						'退货金额'=> array('field'=>'refund_amount','width'=>100),
						'平台退货金额'=> array('field'=>'guarante_refund_amount','width'=>100),//实际退款金额还是申请退款金额
						'线下退货金额'=> array('field'=>'direct_refund_amount','width'=>100),//线下退货金额 退款总金额？
						'换货金额'=> array('field'=>'exchange_amount','width'=>100),//换货金额
						'物流公司'=> array('field'=>'logistics_name','width'=>100),
						'物流单号'=> array('field'=>'logistics_no','width'=>100),
						'退回地址'=> array('field'=>'return_address','width'=>100),
						'建单方式'=> array('field'=>'from_type','width'=>100,'formatter'=>'formatter.trade_from'),
						'退货原因'=> array('field'=>'reason_id','width'=>100),
						'同步结果'=> array('field'=>'sync_result','width'=>100),
						'备注'=> array('field'=>'remark','width'=>100),
				),
				'trade_merge'=>array(
						'平台'=> array('field'=>'platform_id','width'=>100,'formatter'=>'formatter.platform_id'),
						'店铺'=> array('field'=>'shop_id','width'=>150),
						'仓库'=> array('field'=>'warehouse_id','width'=>100),
						'订单编号'=> array('field'=>'trade_no','width'=>100),
						'订单状态'=> array('field'=>'trade_status','width'=>100,'formatter'=>'formatter.trade_status'),
						'客户网名'=> array('field'=>'buyer_nick','width'=>100),
						'收件人'=> array('field'=>'receiver_name','width'=>100),
						'收件人地区'=> array('field'=>'receiver_area','width'=>100),
						'收件人地址'=> array('field'=>'receiver_address','width'=>100),
						'递交时间'=> array('field'=>'created','width'=>100),//递交时间
						'业务员'=> array('field'=>'salesman_id','width'=>100),
						'打印备注'=> array('field'=>'print_remark','width'=>100),//打印备注
						'手机'=> array('field'=>'receiver_mobile','width'=>100),
						'电话'=> array('field'=>'receiver_telno','width'=>100),
						'物流公司'=> array('field'=>'logistics_id','width'=>100),
				),
				'trade_remark'=>array(
						'原始单号'=> array('field'=>'tid','width'=>100),
						'备注'=> array('field'=>'remark','width'=>150),//备注api_trade_remark_history.remark
						'下载时间'=> array('field'=>'created','width'=>100),//下载时间
				),
				'log'=>array(
						'操作员'=> array('field'=>'operator_id','width'=>80),
						'操作'=> array('field'=>'message','width'=>200),
						'时间'=> array('field'=>'created','width'=>80),
				),
				//选择-订单-货品
				'order_list'=>array(
						'平台'=> array('field'=>'platform_id','width'=>100,'formatter'=>'formatter.platform_id'),
						'货品名称'=> array('field'=>'goods_name','width'=>150),
						'规格名'=> array('field'=>'spec_name','width'=>100),
						'原始订单号'=> array('field'=>'src_tid','width'=>100),
						'子订单编号'=> array('field'=>'src_oid','width'=>100),//
						'商家编号'=> array('field'=>'spec_no','width'=>100),
						'货品编号'=> array('field'=>'goods_no','width'=>100),
						'规格码'=> array('field'=>'spec_code','width'=>100),
						'标价'=> array('field'=>'price','width'=>100),
						'优惠'=> array('field'=>'discount','width'=>100),
						'成交价'=> array('field'=>'order_price','width'=>100),
						'分摊后的价格'=> array('field'=>'share_price','width'=>100),
				),
				//退换单
				'refund_order'=>array(
						'平台'=>array('field'=>'platform_id','width'=>100,'formatter'=>'formatter.platform_id'),
						'订单编号'=>array('field'=>'trade_no','width'=>100),
						'原始订单号'=>array('field'=>'tid','width'=>100),
						'子订单号'=>array('field'=>'oid','width'=>100),
						'数量'=>array('field'=>'order_num','width'=>100),
						'价格'=>array('field'=>'price','width'=>100),
						'退款总额'=>array('field'=>'total_amount','width'=>100),
						'商家编码'=>array('field'=>'spec_no','width'=>100),
						'货品编号'=>array('field'=>'goods_no','width'=>100),
						'货品名称'=>array('field'=>'goods_name','width'=>100),
						'规格名'=>array('field'=>'spec_name','width'=>100),
						'组合装名'=>array('field'=>'suite_name','width'=>100),
						'组合装数量'=>array('field'=>'suite_num','width'=>100),
						'入库数量'=>array('field'=>'stockin_num','width'=>100),
						'退款数量'=>array('field'=>'refund_num','width'=>100),
						'备注'=>array('field'=>'remark','width'=>100),
						'原价'=>array('field'=>'original_price','width'=>100),
						'已付金额'=>array('field'=>'paid','width'=>100),
						'优惠'=>array('field'=>'discount','width'=>100),
				),
				'api_order'=>array(
						'子订单号'=>array('field'=>'oid','width'=>100),
						'货品名称'=>array('field'=>'goods_name','width'=>120),
						'规格'=>array('field'=>'spec_name','width'=>120),
						'货品ID'=>array('field'=>'goods_id','width'=>120),
						'规格ID'=>array('field'=>'spec_id','width'=>120),
						'货品商家编码'=>array('field'=>'goods_no','width'=>100),
						'规格商家编码'=>array('field'=>'spec_no','width'=>100),
						'数量'=>array('field'=>'num','width'=>60),
						'价格'=>array('field'=>'price','width'=>80),
						'折扣'=>array('field'=>'discount','width'=>60),
						'总价'=>array('field'=>'share_amount','width'=>80),
				),
				'sales_trade'=>array(
						'订单号'   => array('field'=>'trade_no','width'=>100),
						'店铺名称'  => array('field'=>'shop_id','width'=>100),
						'原始单号'  => array('field'=>'src_tids','width'=>150),
						'客户网名'   => array('field'=>'buyer_nick','width'=>100),
						'收件人'  => array('field'=>'receiver_name','width'=>80),
						'地区'  => array('field'=>'receiver_area','width'=>150),
						'地址'  => array('field'=>'receiver_address','width'=>150),
						'电话'  => array('field'=>'receiver_mobile','width'=>100),
						'邮编'  => array('field'=>'receiver_zip','width'=>100),
						'发货条件'  => array('field'=>'delivery_term','width'=>100,'formatter'=>'formatter.delivery_term'),
						'退货状态'  => array('field'=>'refund_status','width'=>100,'formatter'=>'formatter.refund_status'),
						'仓库'  => array('field'=>'warehouse_id','width'=>100),
						'物流公司'  => array('field'=>'logistics_id','width'=>100),
						'客服备注'  => array('field'=>'cs_remark','width'=>100),
						'买家留言'  => array('field'=>'buyer_message','width'=>100),
						'打印备注'  => array('field'=>'print_remark','width'=>100),
						'货品种类数'  => array('field'=>'goods_type_count','width'=>100),
						'货品总量'  => array('field'=>'goods_count','width'=>100),
						'总货款'  => array('field'=>'goods_amount','width'=>100),
						'邮费'  => array('field'=>'post_amount','width'=>100),
						'优惠'  => array('field'=>'discount','width'=>100),
						'应收'  => array('field'=>'receivable','width'=>100),
						'已付'  => array('field'=>'paid','width'=>100),
						'货到付款金额'  => array('field'=>'dap_amount','width'=>100),
						'买家COD费用'  => array('field'=>'cod_amount','width'=>100),
						//'佣金'  => array('field'=>'commission','width'=>100),
						//'邮费成本'  => array('field'=>'post_cost','width'=>100),
						'货品估算成本'  => array('field'=>'goods_cost','width'=>100),
						'估重'  => array('field'=>'weight','width'=>100),
						'需要发票'  => array('field'=>'invoice_type','width'=>100,'formatter'=>'formatter.invoice_type'),
						'发票抬头'  => array('field'=>'invoice_title','width'=>100),
						'发票内容'  => array('field'=>'invoice_content','width'=>100),
						'下单时间'  => array('field'=>'trade_time','width'=>100),
						'付款时间'  => array('field'=>'pay_time','width'=>100),
						'支付账户'  => array('field'=>'pay_account','width'=>100),
						'送货时间'  => array('field'=>'to_deliver_time','width'=>100),
						'业务员'  => array('field'=>'salesman_id','width'=>100),
						'类型'  => array('field'=>'trade_type','width'=>100,'formatter'=>'formatter.trade_type'),
						'订单来源'  => array('field'=>'trade_from','width'=>100,'formatter'=>'formatter.trade_from'),
						'递交时间'  => array('field'=>'created','width'=>100),
				),
				'fc_reason'=>array(
						'操作人' => array('field'=>'checker','width'=>100),
						'进财审原因' => array('field'=>'message','width'=>200),
						'创建时间' => array('field'=>'created','width'=>100),
				),
				//原始退款单
				'api_refund_goods'=>array(
						'平台' => array('field'=>'platform_id','width'=>100,'formatter'=>'formatter.platform_id'),
						'原始子订单号' => array('field'=>'oid','width'=>100),
						'平台状态' => array('field'=>'status','width'=>100,'formatter'=>'formatter.api_refund_status'),
						'货品ID' => array('field'=>'goods_id','width'=>100),
						'规格ID' => array('field'=>'spec_id','width'=>100),
						'货品编号' => array('field'=>'goods_no','width'=>100),
						'规格码' => array('field'=>'spec_no','width'=>100),
						'货品名称' => array('field'=>'goods_name','width'=>100),
						'规格名称' => array('field'=>'spec_name','width'=>100),
						'数量' => array('field'=>'num','width'=>100),
						'价格' => array('field'=>'price','width'=>100),
						'总额' => array('field'=>'total_amount','width'=>100),
						'备注' => array('field'=>'remark','width'=>100),
						'修改时间' => array('field'=>'modified','width'=>100),
						'创建时间' => array('field'=>'created','width'=>100),
				),
		);
		return $fields[$key];
	}
}