<?php
/**
 * Created by PhpStorm.
 * User: gaosong
 * Date: 11/20/15
 * Time: 10:56
 */
namespace Stock\Field;

use Common\Common\Field;

class StockCommonField extends Field
{
    protected function get($key)
    {
        $fields = array(
            'stock_log' => array(
                'id' => array('field' => 'id', 'hidden' => true),
                '操作员' => array('field' => 'operator_id', 'width' => '100'),
                '操作' => array('field' => 'message', 'width' => '800'),
                '时间' => array('field' => 'created', 'width' => '200'),
            ),
            'stockout_order_detail' => array(
                'id' => array('field' => 'id', 'hidden' => true),
                '商家编码' => array('field' => 'spec_no', 'width' => '100'),
                '货品编号' => array('field' => 'goods_no', 'width' => '100'),
                '货品名称' => array('field' => 'goods_name', 'width' => '100'),
                '规格码' => array('field' => 'spec_code', 'width' => '100'),
                '规格名称' => array('field' => 'spec_name', 'width' => '100'),
                '货位' => array('field' => 'position_no', 'width' => '100'),
                '品牌' => array('field' => 'brand_id', 'width' => '100'),
                '平台货品名称' => array('field' => 'api_goods_name', 'width' => '100'),
                '平台规格名称' => array('field' => 'api_spec_name', 'width' => '100'),
                '条形码' => array('field' => 'barcode', 'width' => '100'),
                '标价' => array('field' => 'price', 'width' => '100'),
                '成交价' => array('field' => 'order_price', 'width' => '100'),
                '已付' => array('field' => 'paid', 'width' => '100'),
                '数量' => array('field' => 'num', 'width' => '100'),
                '组合装名称' => array('field' => 'suite_name', 'width' => '100'),
                '组合装编码' => array('field' => 'suite_no', 'width' => '100'),
                '组合装数量' => array('field' => 'suite_num', 'width' => '100'),
                '估重' => array('field' => 'weight', 'width' => '100'),
//                 '验货方式' => array('field' => 'scan_type', 'width' => '100'),
                '备注' => array('field' => 'remark', 'width' => '100',)
            ),
            //添加图片字段
            'stocksales_print_detail' => array(
                'id' => array('field' => 'id', 'hidden' => true),
                '商家编码' => array('field' => 'spec_no', 'width' => '100'),
                '货品编号' => array('field' => 'goods_no', 'width' => '100'),
                '图片' => array('field' => 'img_url', 'width' => '100','formatter'=>'formatter.print_img'),
                '货品名称' => array('field' => 'goods_name', 'width' => '100'),
                '规格码' => array('field' => 'spec_code', 'width' => '100'),
                '规格名称' => array('field' => 'spec_name', 'width' => '100'),
                '货位' => array('field' => 'position_no', 'width' => '100'),
                '品牌' => array('field' => 'brand_id', 'width' => '100'),
                '平台货品名称' => array('field' => 'api_goods_name', 'width' => '100'),
                '平台规格名称' => array('field' => 'api_spec_name', 'width' => '100'),
                '条形码' => array('field' => 'barcode', 'width' => '100'),
                '标价' => array('field' => 'price', 'width' => '100'),
                '成交价' => array('field' => 'order_price', 'width' => '100'),
                '已付' => array('field' => 'paid', 'width' => '100'),
                '数量' => array('field' => 'num', 'width' => '100'),
                '组合装名称' => array('field' => 'suite_name', 'width' => '100'),
                '组合装编码' => array('field' => 'suite_no', 'width' => '100'),
                '组合装数量' => array('field' => 'suite_num', 'width' => '100'),
                '估重' => array('field' => 'weight', 'width' => '100'),
//                 '验货方式' => array('field' => 'scan_type', 'width' => '100'),
                '备注' => array('field' => 'remark', 'width' => '100',)
            ),
			'stock_trans_detail' =>array(
				'id' => array('field' => 'id', 'hidden' => true),
                '商家编码' => array('field' => 'spec_no', 'width' => '100'),
                '货品编号' => array('field' => 'goods_no', 'width' => '100'),
                '货品名称' => array('field' => 'goods_name', 'width' => '100'),
                '货品简称' => array('field' => 'short_name', 'width' => '100'),
                '规格码' => array('field' => 'spec_code', 'width' => '100'),
                '规格名称' => array('field' => 'spec_name', 'width' => '100'),
				'品牌' => array('field' => 'brand_id', 'width' => '100'),
				'条形码' => array('field' => 'barcode', 'width' => '100'),
				'库存数量' => array('field' => 'stock_num', 'width' => '100'),
			    '调拨数量' => array('field' => 'num', 'width' => '100'),
			    '调出货位' => array('field' => 'from_position_no', 'width' => '100'),
			    '调入货位' => array('field' => 'to_position_no', 'width' => '100'),
			    '已出库数量' => array('field' => 'out_num', 'width' => '100'),
			    '已入库数量' => array('field' => 'in_num', 'width' => '100'),
				'备注' => array('field' => 'remark', 'width' => '100'),
            ),
            'api_logistics_sync_detail'=>array(
                'id'      =>array('field'=>'id','hidden'=>true),
                '货品编号'=>array('field'=>'goods_no','width'=>'100'),
                '货品名称'=>array('field'=>'goods_name','width'=>'100'),
                '商家编码'=>array('field'=>'spec_no','width'=>'100'),
                '规格名称'=>array('field'=>'spec_name','width'=>'100'),
                '成交价'=>array('field'=>'order_price','width'=>'100'),
                '货品数量'=>array('field'=>'num','width'=>'100'),
                '货品总额'=>array('field'=>'sum_price','width'=>'100'),
				),
            'salestradedetail' => array(
                'id' => array('field' => 'id', 'hidden' => true),
                '订单编号' => array('field' => 'trade_no', 'width' => '100'),
                '订单状态' => array('field' => 'trade_status', 'width' => '100', 'formatter' => 'formatter.trade_status',),
                '交易时间' => array('field' => 'trade_time', 'width' => '150'),
                '商家编码' => array('field' => 'spec_no', 'width' => '100'),
                '货品编号' => array('field' => 'goods_no', 'width' => '100'),
                '货品名称' => array('field' => 'goods_name', 'width' => '100'),
                '规格码' => array('field' => 'spec_code', 'width' => '100'),
                '规格名称' => array('field' => 'spec_name', 'width' => '100'),
                '数量' => array('field' => 'actual_num', 'width' => '100'),
            ),
            'api_logistics_sync_detail'=>array(
                'id'      =>array('field'=>'id','hidden'=>true),
                '货品编号'=>array('field'=>'goods_no','width'=>'100'),
                '货品名称'=>array('field'=>'goods_name','width'=>'100'),
                '商家编码'=>array('field'=>'spec_no','width'=>'100'),
                '规格名称'=>array('field'=>'spec_name','width'=>'100'),
                '成交价'=>array('field'=>'order_price','width'=>'100'),
                '货品数量'=>array('field'=>'num','width'=>'100'),
                '货品总额'=>array('field'=>'sum_price','width'=>'100'),
            ),
            'sales_multi_logistics'=>array(
                'id'      =>array('field'=>'id','hidden'=>true),
                '操作者'=>array('field'=>'operator','width'=>'100'),
                '物流公司'=>array('field'=>'logistics','width'=>'100'),
                'logistics_id'=>array('field'=>'logistics_id','hidden'=>true),
                '物流单号'=>array('field'=>'logistics_no','width'=>'100'),
                '打印状态'=>array('field'=>'print_status','width'=>'100','formatter' => 'formatter.multiple_print_status'),
                '重量(kg)'=>array('field'=>'weight','width'=>'100'),
				'邮资'=>array('field'=>'post_cost','width'=>'100'),
				'修改日期'=>array('field'=>'modified','width'=>'100'),
                '创建日期'=>array('field'=>'created','width'=>'100'),
                '物流类型'=>array('field'=>'logistics_type','hidden'=>true),

            ),
            'stocksync' => array(
                '店铺'       => array('field' => 'shop_id', 'width' => 100),
                '平台货品商家编码' => array('field' => 'outer_id', 'width' => 100),
                '平台货品ID'   => array('field' => 'goods_id', 'width' => 100),
                '平台规格ID'   => array('field' => 'spec_id', 'width' => 100),
                '平台货品名称'   => array('field' => 'api_goods_name', 'width' => 100),
                '平台规格商家编码' => array('field' => 'spec_outer_id', 'width' => 100),
                '平台规格名称'   => array('field' => 'api_spec_name', 'width' => 100),
                '货品商家编码'   => array('field' => 'spec_no', 'width' => 100),
                '货品类型'     => array('field' => 'goods_type', 'width' => 100),
                '同步数量'     => array('field' => 'syn_stock', 'width' => 100),
                '同步规则编号'   => array('field' => 'stock_syn_rule_no', 'width' => 100),
                '同步仓库'     => array('field' => 'stock_syn_warehouses', 'width' => 100, 'formatter' => 'tabsWarehouseFormatter'),
                '同步数量计算方式' => array('field' => 'stock_syn_mask', 'width' => 100),
                '同步百分比'    => array('field' => 'stock_syn_percent', 'width' => 100),
                '同步附加量'    => array('field' => 'stock_syn_plus', 'width' => 100),
                '最小同步量'    => array('field' => 'stock_syn_min', 'width' => 100),
                '自动上架'     => array('field' => 'is_auto_listing', 'width' => 100),
                '自动下架'     => array('field' => 'is_auto_delisting', 'width' => 100),
                '是否同步成功'   => array('field' => 'is_syn_sucess', 'width' => 100),
                '同步结果'     => array('field' => 'syn_result', 'width' => 100),
                '同步方式'     => array('field' => 'syn_type', 'width' => 100),
                '同步时间'     => array('field' => 'created', 'width' => 100),
            ),
            'warehousestockdetail'=>array(
                'id'=>array('field'=>'id','hidden'=>true,),
//                '商家编码'=>array('field'=>'spec_no','width'=>'100'),
//                '货品编号'=>array('field'=>'goods_no','width'=>'100'),
//                '货品名称'=>array('field'=>'goods_name','width'=>'100'),
//                '货品简称'=>array('field'=>'short_name','width'=>'100'),
//                '规格码'=>array('field'=>'spec_code','width'=>'100'),
//                '规格名称'=>array('field'=>'spec_name','width'=>'100'),
//                '条形码'=>array('field'=>'barcode','width'=>'100'),
//                '品牌'=>array('field'=>'brand_id','width'=>'100'),
//                '分类'=>array('field'=>'class_id','width'=>'100'),
                '仓库名称'=>array('field'=>'warehouse_name','width'=>'100'),
                '仓库id'=>array('field'=>'warehouse_id','width'=>'100','hidden'=>true),
                '仓库类别'=>array('field'=>'warehouse_type','width'=>'100','formatter'=>'formatter.warehouse_type'),
                '库存'=>array('field'=>'stock_num','width'=>'100'),
				'货位'=>array('field'=>'position_no','width'=>'100'),
                '成本价'=>array('field'=>'cost_price','width'=>'100'),
                '总成本'=>array('field'=>'all_cost_price','width'=>'100'),
                '可发库存'=>array('field'=>'avaliable_num','width'=>'100'),
//				'锁定量'=>array('field'=>'lock_num','width'=>'100'),
//                 '警戒库存'=>array('field'=>'safe_stock','width'=>'100'),
//                 '警戒天数'=>array('field'=>'alarm_days','width'=>'100'),
//                 '未付款量'=>array('field'=>'unpay_num','width'=>'100'),
//                 '预订单量'=>array('field'=>'subscribe_num','width'=>'100'),
                '待审核量'=>array('field'=>'order_num','width'=>'100'),
                '待发货量'=>array('field'=>'sending_num','width'=>'100'),
                '预订单量'=>array('field'=>'subscribe_num','width'=>'100'),
                '警戒库存'=>array('field'=>'safe_stock','width'=>'100','align'=>'center'),
                '警戒天数'=>array('field'=>'alarm_days','width'=>'100','align'=>'center'),
//                 '待采购量'=>array('field'=>'to_purchase_num','width'=>'100'),
//                 '采购在途'=>array('field'=>'purchase_num','width'=>'100'),
//                 '采购到货量'=>array('field'=>'purchase_arrive_num','width'=>'100'),
//				'待调拨量'=>array('field'=>'to_transfer_num','width'=>'100'),
//                 '调拨在途'=>array('field'=>'transfer_num','width'=>'100'),
//                 '采购退货'=>array('field'=>'return_num','width'=>'100'),
                '零售价'=>array('field'=>'retail_price','width'=>'100'),
                '市场价'=>array('field'=>'market_price','width'=>'100'),
//                 '备注'=>array('field'=>'remark','width'=>'100'),
//				'仓储编码'=>array('field'=>'spec_wh_no','width'=>'100'),
//				'仓储库存'=>array('field'=>'wms_sync_stock','width'=>'100'),
//				'库存差异'=>array('field'=>'wms_stock_diff','width'=>'100'),
//				'同步时间'=>array('field'=>'wms_sync_time','width'=>'100'),
            ),
            'stockpddetailspecifics'=>array(
                        'id'=>array('field'=>'id','hidden'=>true),
                        '商家编码'=>array('field'=>'spec_no','width'=>'100','formatter'=>'formatter.spec_no'),
                        '条码'=>array('field' => 'barcode','width'=>'100'),
                        '货品编号'=>array('field'=>'goods_no','width'=>'100'),
                        '货品名称'=>array('field'=>'goods_name','width'=>'150'),
                        '规格码'=>array('field'=>'spec_code','width'=>'100'),
                        '规格名称'=>array('field'=>'spec_name','width'=>'100'),
                        '货位' => array('field'=>'position_no','witdh'=>'100'),
                        '原始库存' => array('field'=>'old_num','width'=>'100'),
                        '盘点数量' => array('field'=>'new_num','width'=>'100'),
                        '盈余数量' => array('field'=>'yk_num','width'=>'100'),
                        '盈余金额'=>array('field'=>'total_price','width'=>'100'),
                        '备注'=>array('field'=>'remark','width'=>'100'),
            ),
            'stockspeclog'=>array(
                        'id'=>array('field'=>'id','hidden'=>true),
                        '仓库'=>array('field'=>'warehouse_name','width'=>'10%',),
                        '操作者'=>array('field' => 'fullname','width'=>'10%'),
                        '操作日志'=>array('field'=>'message','width'=>'60%'),
                        '操作时间'=>array('field'=>'created','width'=>'20%'),
            ),
        );
        return $fields[$key];
    }
}